export const CAT_BREEDS = [
  'Agouti',
  'Bi-color',
  'Calico',
  'Chinchilla',
  'Colorpoint',
  'Cream Tabby',
  'Dilute Calico',
  'Dilute Tortie',
  'Fawn',
  'Harlequin',
  'Lynx Point',
  'Mackerel Tabby',
  'Marbled',
  'Mitted',
  'Mixed',
  'Patched Tabby',
  'Pointed',
  'Rosetted',
  'Self-colored',
  'Shaded',
  'Silver Tabby',
  'Smoke',
  'Solid',
  'Spotted',
  'Tabby',
  'Tabby with White',
  'Tortoiseshell',
  'Torbie',
  'Tricolor',
  'Tuxedo',
  'Van Pattern',
  'Whisker Spotting',
];
